package generator

import (
	"fmt"
	"strings"

	"gen-swagger-doc/pkg/driver"
)

// GenerateSwaggerDocs 根据路由信息生成 Swagger 注释块
// 返回的切片不包含 "// " 前缀，调用方应根据需要添加
func GenerateSwaggerDocs(route driver.RouteInfo, params []driver.ParamInfo, responses []driver.ResponseInfo) []string {
	var lines []string

	// 1. @Summary (暂用 HandlerName 或 Path 占位，通常应该由上层传入或通过 SummaryParser 解析)
	// 这里为了简单，如果 route 中没有提供额外描述，就用 Path + Method
	lines = append(lines, fmt.Sprintf("@Summary %s %s", route.Method, route.Path))

	// 2. @Description
	lines = append(lines, "@Description auto-generated by gen-swagger-doc")

	// 3. @Tags (暂无)
	// lines = append(lines, "@Tags ...")

	// 4. @Accept / @Produce (默认 JSON)
	lines = append(lines, "@Accept json")
	lines = append(lines, "@Produce json")

	// 5. @Param
	for _, p := range params {
		// 格式: @Param name in type required desc schema
		// e.g. @Param id path int true "User ID"
		reqStr := "false"
		if p.Required {
			reqStr = "true"
		}

		var line string
		if p.In == "body" {
			// Body 参数: @Param name body Schema true "desc"
			// 注意: Body 参数通常不需要 type (string/int)，而是直接跟 Schema
			line = fmt.Sprintf("@Param %s %s %s %s \"%s\"", p.Name, p.In, p.Schema, reqStr, p.Desc)
		} else {
			// 普通参数: @Param name query string true "desc"
			line = fmt.Sprintf("@Param %s %s %s %s \"%s\"", p.Name, p.In, p.Type, reqStr, p.Desc)
		}
		
		lines = append(lines, line)
	}

	// 6. @Success / @Failure
	if len(responses) == 0 {
		// 默认响应
		lines = append(lines, "@Success 200 {object} map[string]interface{}")
	} else {
		for _, r := range responses {
			// 格式: @Success 200 {object} UserResponse "desc"
			schemaType := "object"
			if r.IsArray {
				schemaType = "array"
			}
			
			// 如果 Schema 为空，给一个默认值，否则 swag 可能报错
			schema := r.Schema
			if schema == "" {
				schema = "string"
				schemaType = "string"
			}

			line := fmt.Sprintf("@Success %d {%s} %s", r.Code, schemaType, schema)
			if r.Desc != "" {
				line += fmt.Sprintf(" \"%s\"", r.Desc)
			}
			lines = append(lines, line)
		}
	}

	// 7. @Router (必须在最后)
	// 格式: @Router /path [method]
	lines = append(lines, fmt.Sprintf("@Router %s [%s]", route.Path, strings.ToLower(route.Method)))

	return lines
}
